spring:
  application:
    name: feilu-shop-es-api
  datasource:
    system:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://106.54.174.9/feilu_system?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: fldev
      password: Fei5151309
    site:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://106.54.174.9/feilu_website?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: fldev
      password: Fei5151309
  task:
    scheduling:
      pool:
        # 任务线程池
        size: 5

server:
  port: 8080

# elasticsearch config
es:
  host: 127.0.0.1
  port: 9200


redis:
  host: localhost
  port: 6379
  pool:
    maxTotal: 10 #最大连接数
    maxIdle: 5 #最大空闲连接数
    minIdle: 1 #最小空闲连接数
  # 同步订单队列key 新系统:whatsappOrderConfirm  pdd:whatsappOrderConfirm_pdd
  queue:
    synOrderKey: syncOrder
    whatsapp:
      orderConfirmKey: whatsappOrderConfirm

# 任务相关cron  如果暂时关闭定时任务可以把 cron 改为 "-"
scheduled:
  cron:
    updateDataModelTaskCron: 0 40 1 * * ?

